# .github/workflows/deploy-azure-arm.yml

name: Deploy Azure ARM Template
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with:
          azcliversion: 2.28.0
          inlineScript: |
            az deployment sub create \
              --location WestUS
              --template-file core/staticdeploy.json \
              
