# .github/workflows/deploy-azure-arm.yml

name: Destroy Azure ARM infra Template
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ARM Template Toolkit (ARM TTK) Validation
        id: armttkvalidation
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: infra/webapp-arm.json 

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Destroy Azure Resource
        run: |
          az deployment group delete \
            --name webapp-arm \
            --resource-group njb1210 \
            --yes